import { StyleSheet } from "react-native";

const bloomColors = {
  coral: "#F0655A",
  cream: "#FAF3E7",
  gold: "#F7B92B",
  hairline: "rgba(58, 46, 63, 0.12)",
  plum: "#3A2E3F",
  soft: "#8D8494",
  teal: "#2FB9A5",
} as const;

export const styles = StyleSheet.create({
  blobBody: {
    backgroundColor: bloomColors.coral,
    borderBottomLeftRadius: 86,
    borderBottomRightRadius: 62,
    borderTopLeftRadius: 92,
    borderTopRightRadius: 70,
    height: 168,
    width: 176,
  },
  blobDot: {
    backgroundColor: bloomColors.coral,
    borderRadius: 999,
    height: 16,
    width: 16,
  },
  blobDotWrap: {
    alignItems: "center",
    paddingVertical: 10,
  },
  blobHalo: {
    backgroundColor: bloomColors.gold,
    borderBottomLeftRadius: 74,
    borderBottomRightRadius: 104,
    borderTopLeftRadius: 84,
    borderTopRightRadius: 96,
    height: 200,
    opacity: 0.4,
    position: "absolute",
    width: 206,
  },
  blobWrap: {
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: 8,
    paddingTop: 18,
  },
  checkbox: {
    alignItems: "center",
    borderColor: bloomColors.soft,
    borderRadius: 8,
    borderWidth: 1.5,
    height: 26,
    justifyContent: "center",
    width: 26,
  },
  checkboxChecked: {
    backgroundColor: bloomColors.teal,
    borderColor: bloomColors.teal,
  },
  checkboxMark: {
    color: bloomColors.cream,
    fontSize: 15,
    fontWeight: "700",
  },
  chrome: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 24,
    paddingTop: 10,
  },
  chromeButtonText: {
    color: bloomColors.soft,
    fontSize: 22,
    letterSpacing: 2,
    lineHeight: 24,
  },
  consentRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 14,
    paddingVertical: 16,
  },
  controlColumn: {
    alignItems: "center",
    gap: 12,
    paddingBottom: 16,
    paddingTop: 12,
  },
  copy: {
    color: bloomColors.soft,
    fontSize: 16,
    lineHeight: 25,
  },
  error: {
    color: bloomColors.coral,
    fontSize: 14,
    lineHeight: 20,
    paddingHorizontal: 24,
    textAlign: "center",
  },
  eyebrow: {
    color: bloomColors.teal,
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 0.4,
  },
  flexFill: {
    flex: 1,
  },
  languageRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
  },
  languageText: {
    color: bloomColors.plum,
    fontSize: 17,
    fontWeight: "700",
  },
  listenPill: {
    alignItems: "center",
    backgroundColor: bloomColors.coral,
    borderRadius: 999,
    elevation: 6,
    minHeight: 58,
    minWidth: 200,
    justifyContent: "center",
    paddingHorizontal: 36,
    shadowColor: bloomColors.coral,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
  },
  listenPillText: {
    color: bloomColors.cream,
    fontSize: 18,
    fontWeight: "800",
  },
  modeTab: {
    color: bloomColors.soft,
    fontSize: 15,
    fontWeight: "600",
  },
  modeTabActive: {
    color: bloomColors.plum,
    fontSize: 15,
    fontWeight: "800",
  },
  modeTabs: {
    alignItems: "center",
    flexDirection: "row",
    gap: 18,
  },
  onboardingBody: {
    flex: 1,
    gap: 18,
    justifyContent: "center",
    paddingHorizontal: 28,
  },
  onboardingFooter: {
    alignItems: "center",
    paddingBottom: 26,
    paddingHorizontal: 28,
    paddingTop: 10,
  },
  pressed: {
    opacity: 0.55,
  },
  receipt: {
    color: bloomColors.teal,
    fontSize: 14,
    paddingHorizontal: 24,
    textAlign: "center",
  },
  rtlText: {
    textAlign: "right",
    writingDirection: "rtl",
  },
  screen: {
    backgroundColor: bloomColors.cream,
    flex: 1,
  },
  setupRow: {
    borderBottomColor: bloomColors.hairline,
    borderBottomWidth: 1.5,
    gap: 6,
    paddingVertical: 18,
  },
  setupValue: {
    color: bloomColors.plum,
    fontSize: 24,
    fontWeight: "700",
  },
  sourceText: {
    color: bloomColors.soft,
    fontSize: 16,
    lineHeight: 24,
  },
  stage: {
    flexGrow: 1,
    gap: 14,
    justifyContent: "center",
    paddingHorizontal: 28,
  },
  swapText: {
    color: bloomColors.teal,
    fontSize: 19,
    fontWeight: "700",
  },
  timelineContent: {
    gap: 18,
    paddingBottom: 20,
    paddingHorizontal: 28,
    paddingTop: 8,
  },
  timelineTranslation: {
    color: bloomColors.plum,
    fontSize: 22,
    fontWeight: "700",
    lineHeight: 31,
  },
  title: {
    color: bloomColors.plum,
    fontSize: 32,
    fontWeight: "800",
    lineHeight: 40,
  },
  translationPartial: {
    opacity: 0.5,
  },
  translationText: {
    color: bloomColors.plum,
    fontSize: 32,
    fontWeight: "800",
    lineHeight: 42,
    textAlign: "center",
  },
  wordmark: {
    color: bloomColors.plum,
    fontSize: 17,
    fontWeight: "800",
  },
});
