import { StyleSheet } from "react-native";

const bloomColors = {
  coral: "#F0655A",
  cream: "#FAF3E7",
  gold: "#F7B92B",
  hairline: "rgba(58, 46, 63, 0.12)",
  plum: "#3A2E3F",
  soft: "#8D8494",
  surface: "#FFFDF9",
  teal: "#2FB9A5",
  violet: "#8662E6",
} as const;

export const styles = StyleSheet.create({
  checkbox: {
    alignItems: "center",
    borderColor: bloomColors.soft,
    borderRadius: 8,
    borderWidth: 1.5,
    height: 26,
    justifyContent: "center",
    width: 26,
  },
  checkboxChecked: {
    backgroundColor: bloomColors.teal,
    borderColor: bloomColors.teal,
  },
  checkboxMark: {
    color: bloomColors.cream,
    fontSize: 15,
    fontWeight: "700",
  },
  chrome: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  captionSurface: {
    backgroundColor: bloomColors.surface,
    borderColor: bloomColors.hairline,
    borderRadius: 28,
    borderWidth: 1,
    flex: 1,
    marginHorizontal: 18,
    marginTop: 12,
    overflow: "hidden",
  },
  consentRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 14,
    paddingVertical: 16,
  },
  controlColumn: {
    alignItems: "stretch",
    backgroundColor: bloomColors.surface,
    borderTopColor: bloomColors.hairline,
    borderTopWidth: 1,
    gap: 12,
    paddingBottom: 18,
    paddingHorizontal: 20,
    paddingTop: 14,
  },
  copy: {
    color: bloomColors.soft,
    fontSize: 16,
    lineHeight: 25,
  },
  error: {
    color: bloomColors.coral,
    fontSize: 14,
    lineHeight: 20,
    paddingHorizontal: 24,
    textAlign: "center",
  },
  eyebrow: {
    color: bloomColors.teal,
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 0.4,
  },
  flexFill: {
    flex: 1,
  },
  languageRow: {
    alignItems: "center",
    alignSelf: "center",
    flexDirection: "row",
    gap: 14,
    minHeight: 28,
  },
  languageText: {
    color: bloomColors.plum,
    fontSize: 15,
    fontWeight: "700",
  },
  listenPill: {
    alignItems: "center",
    backgroundColor: bloomColors.plum,
    borderRadius: 999,
    minHeight: 56,
    justifyContent: "center",
    paddingHorizontal: 24,
    width: "100%",
  },
  listenPillText: {
    color: bloomColors.cream,
    fontSize: 17,
    fontWeight: "800",
  },
  stopPill: {
    backgroundColor: bloomColors.coral,
  },
  modeTab: {
    color: bloomColors.soft,
    fontSize: 15,
    fontWeight: "600",
  },
  modeTabActive: {
    color: bloomColors.plum,
    fontSize: 15,
    fontWeight: "800",
  },
  modeTabs: {
    alignItems: "center",
    flexDirection: "row",
    gap: 18,
  },
  onboardingBody: {
    flex: 1,
    gap: 18,
    justifyContent: "center",
    paddingHorizontal: 32,
  },
  onboardingFooter: {
    alignItems: "stretch",
    paddingBottom: 26,
    paddingHorizontal: 28,
    paddingTop: 10,
  },
  pressed: {
    opacity: 0.55,
  },
  progressDot: {
    backgroundColor: bloomColors.hairline,
    borderRadius: 999,
    height: 5,
    width: 5,
  },
  progressDotActive: {
    backgroundColor: bloomColors.plum,
    width: 20,
  },
  progressRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 6,
    justifyContent: "center",
    paddingTop: 14,
  },
  receipt: {
    color: bloomColors.teal,
    fontSize: 14,
    paddingHorizontal: 24,
    textAlign: "center",
  },
  rtlText: {
    textAlign: "right",
    writingDirection: "rtl",
  },
  screen: {
    backgroundColor: bloomColors.cream,
    flex: 1,
  },
  settingsButton: {
    alignItems: "center",
    backgroundColor: bloomColors.surface,
    borderColor: bloomColors.hairline,
    borderRadius: 21,
    borderWidth: 1,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  settingsGlyph: {
    color: bloomColors.plum,
    fontSize: 17,
    fontWeight: "800",
    letterSpacing: 2,
    lineHeight: 18,
  },
  setupRow: {
    borderBottomColor: bloomColors.hairline,
    borderBottomWidth: 1.5,
    gap: 6,
    paddingVertical: 18,
  },
  setupValue: {
    color: bloomColors.plum,
    fontSize: 24,
    fontWeight: "700",
  },
  sourceText: {
    color: bloomColors.soft,
    fontSize: 15,
    lineHeight: 23,
  },
  signalBar: {
    borderRadius: 999,
    height: 12,
    width: 4,
  },
  signalBarCoral: {
    backgroundColor: bloomColors.coral,
  },
  signalBarGold: {
    backgroundColor: bloomColors.gold,
    height: 18,
  },
  signalBarTeal: {
    backgroundColor: bloomColors.teal,
    height: 16,
  },
  signalBarViolet: {
    backgroundColor: bloomColors.violet,
    height: 10,
  },
  signalWrap: {
    alignItems: "center",
    flexDirection: "row",
    gap: 4,
    justifyContent: "center",
    minHeight: 28,
    paddingTop: 6,
  },
  swapText: {
    color: bloomColors.teal,
    fontSize: 18,
    fontWeight: "700",
  },
  timelineContent: {
    flexGrow: 1,
    gap: 22,
    paddingBottom: 24,
    paddingHorizontal: 26,
    paddingTop: 16,
  },
  timelineTranslation: {
    color: bloomColors.plum,
    fontSize: 30,
    fontWeight: "800",
    lineHeight: 39,
  },
  title: {
    color: bloomColors.plum,
    fontSize: 36,
    fontWeight: "800",
    lineHeight: 44,
  },
  translationPartial: {
    opacity: 0.5,
  },
  wordmark: {
    color: bloomColors.plum,
    fontSize: 18,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  brandMark: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  brandLogo: {
    borderRadius: 10,
    height: 30,
    width: 30,
  },
  heroAccent: {
    borderRadius: 999,
    height: 5,
  },
  heroAccentCoral: {
    backgroundColor: bloomColors.coral,
    width: 12,
  },
  heroAccentGold: {
    backgroundColor: bloomColors.gold,
    width: 20,
  },
  heroAccentRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 5,
    justifyContent: "center",
    marginTop: 12,
  },
  heroAccentTeal: {
    backgroundColor: bloomColors.teal,
    width: 28,
  },
  heroAccentViolet: {
    backgroundColor: bloomColors.violet,
    width: 12,
  },
  heroFrame: {
    alignItems: "center",
    backgroundColor: bloomColors.surface,
    borderColor: bloomColors.hairline,
    borderRadius: 42,
    borderWidth: 1,
    justifyContent: "center",
    padding: 10,
  },
  heroLogo: {
    borderRadius: 32,
    height: 172,
    width: 172,
  },
  heroWrap: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 224,
  },
  liveStatus: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  liveStatusDot: {
    borderRadius: 999,
    height: 8,
    width: 8,
  },
  liveStatusDotLive: {
    backgroundColor: bloomColors.coral,
  },
  liveStatusDotReady: {
    backgroundColor: bloomColors.teal,
  },
  liveStatusText: {
    color: bloomColors.soft,
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
});
